compute_environment: GOOGLE_COLAB
# debug: false
# distributed_type: MULTI_GPU
# main_process_port: 14121
debug: false
distributed_type: NO
main_process_port: 29500
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false